
GET http://localhost:3001/api/patients HTTP/1.1

###
GET http://localhost:3001/api/patients/1 HTTP/1.1

###
POST http://localhost:3001/api/patients/ HTTP/1.1
Content-Type: application/json

{
    "name": "facundo",
    "debt": true,
    "queries": 1,
    "phone": "18253598"  
}

###
PUT  http://localhost:3001/api/patients/8 HTTP/1.1
Content-Type: application/json

{
    "name": "cambio",
    "debt": false,
    "queries": 1
}

###
DELETE   http://localhost:3001/api/patients/8 HTTP/1.1

### BOOKING----------------------------------------------------------
GET http://localhost:3001/api/bookings HTTP/1.1

###

GET http://localhost:3001/api/bookings/3 HTTP/1.1

###

POST http://localhost:3001/api/bookings HTTP/1.1
Content-Type: application/json

{
  "id": 3,
  "name": "mayra",
  "kind": "masaje",
  "phone": "097073584",
  "extra Data": "EJEMPLO"  
}

###

PUT  http://localhost:3001/api/bookings/20 HTTP/1.1
Content-Type: application/json

{
    "name": "ejemplo",
    "kind": "ejemplo",
    "phone": "EJEMPLO",
    "extra Data": "EJEMPLO"  
}

###

PUT  http://localhost:3001/api/bookings/22 HTTP/1.1
Content-Type: application/json

{
    "name": "ejemplo 2",
    "kind": "masaje 2",
    "phone": "EJEMPLO 2",
    "extra Data": "EJEMPLO 2"  
}

###

DELETE   http://localhost:3001/api/bookings/22 HTTP/1.1

### record----------------------------------------------------------
GET http://localhost:3001/api/records HTTP/1.1

###

GET http://localhost:3001/api/records/2/patient HTTP/1.1

###

POST http://localhost:3001/api/records/2/patient HTTP/1.1
Content-Type: application/json

{
  "date": "24/10/2024",
  "hour": "10:00",
  "attendance": true
}

###

PUT  http://localhost:3001/api/records/6 HTTP/1.1
Content-Type: application/json

{
  "date": "25/10/2024 put funcionando",
  "hour": "11:00",
  "attendance": false
}

###

DELETE   http://localhost:3001/api/records/6 HTTP/1.1

###

DELETE   http://localhost:3001/api/records/2/patient HTTP/1.1

FALTA UN put para creear un paciente