GET http://localhost:3001/patients HTTP/1.1

###
GET http://localhost:3001/patients/2 HTTP/1.1

###
POST http://localhost:3001/patients/new HTTP/1.1
Content-Type: application/json

{
    "name": "facundo",
    "debt": true,
    "queries": 1,
    "phone": "18253598"  
}

###
PUT  http://localhost:3001/patients/11 HTTP/1.1
Content-Type: application/json

{
    "name": "facucambio",
    "debt": false,
    "queries": 1
}

###
DELETE   http://localhost:3001/patients/4 HTTP/1.1

### BOOKING----------------------------------------------------------
GET http://localhost:3001/booking HTTP/1.1

###

GET http://localhost:3001/booking/2 HTTP/1.1

###

POST http://localhost:3001/booking/new HTTP/1.1
Content-Type: application/json

{
        "patientID": 2,
        "name": "mayra",
        "kind": "masaje",
        "phone": "097073584",
        "extra Data": "EJEMPLO"  
}

###

PUT  http://localhost:3001/booking/5 HTTP/1.1
Content-Type: application/json

{
    "patientID": 5,
    "name": "ejemplo",
    "kind": "masaje",
    "phone": "EJEMPLO",
    "extra Data": "EJEMPLO"  
}

###

DELETE   http://localhost:3001/booking/5 HTTP/1.1

### record----------------------------------------------------------
GET http://localhost:3001/records HTTP/1.1

###

GET http://localhost:3001/patients/2/records HTTP/1.1

###

POST http://localhost:3001/patients/1/records HTTP/1.1
Content-Type: application/json

{
  "date": "24/10/2024",
  "hour": "10:00",
  "attendance": true
}

###

PUT  http://localhost:3001/patients/1/records/1 HTTP/1.1
Content-Type: application/json

{
  "date": "25/10/2024",
  "hour": "11:00",
  "attendance": false
}

###

DELETE   http://localhost:3001/patients/1/records/4 HTTP/1.1